name: Label PR size

on: pull_request

jobs:
  size-label:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    if: ${{ github.actor != 'dependabot[bot]' }}
    steps:
      - name: size-label
        uses: "pascalgn/size-label-action@v0.5.0"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          IGNORED: "*/drawable/.xml"
        with:
          sizes: >
            {
              "0": "XS",
              "10": "S",
              "100": "M",
              "500": "L",
              "1000": "XL",
              "2000": "XXL"
            }